// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEi7osbK2tyfvvPU9XOKDSEj284_AAGMQ',
    appId: '1:592895213688:web:3b86ff993c6b86ce66ad8d',
    messagingSenderId: '592895213688',
    projectId: 'sss-barcode-generator',
    authDomain: 'sss-barcode-generator.firebaseapp.com',
    storageBucket: 'sss-barcode-generator.firebasestorage.app',
    measurementId: 'G-CDG88QT3ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxF-F9fqIJQ94wC73GiuPSmDKhy6l1Rsc',
    appId: '1:592895213688:android:fd2138917298827866ad8d',
    messagingSenderId: '592895213688',
    projectId: 'sss-barcode-generator',
    storageBucket: 'sss-barcode-generator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLcq5zdbaQjelO2gkUxK5bBIwA93SsTBk',
    appId: '1:592895213688:ios:4f84f6c99428580a66ad8d',
    messagingSenderId: '592895213688',
    projectId: 'sss-barcode-generator',
    storageBucket: 'sss-barcode-generator.firebasestorage.app',
    iosBundleId: 'com.example.sssBarcodeIdGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLcq5zdbaQjelO2gkUxK5bBIwA93SsTBk',
    appId: '1:592895213688:ios:4f84f6c99428580a66ad8d',
    messagingSenderId: '592895213688',
    projectId: 'sss-barcode-generator',
    storageBucket: 'sss-barcode-generator.firebasestorage.app',
    iosBundleId: 'com.example.sssBarcodeIdGenerator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEi7osbK2tyfvvPU9XOKDSEj284_AAGMQ',
    appId: '1:592895213688:web:cd7f644dd2c3e6ef66ad8d',
    messagingSenderId: '592895213688',
    projectId: 'sss-barcode-generator',
    authDomain: 'sss-barcode-generator.firebaseapp.com',
    storageBucket: 'sss-barcode-generator.firebasestorage.app',
    measurementId: 'G-T4715SPJXD',
  );
}
